=begin
    
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    
=end

# generate terms

numbers = [1,2] 

(1..200).each do |counter|
    if numbers[counter] + numbers[counter-1] > 4000000
        break
    else
        numbers[counter+1] = numbers[counter] + numbers[counter-1]
    end
end

#puts numbers

addition = 0
numbers.each_index do |count|
    if numbers[count]%2 == 0
        addition += numbers[count]        
    end
end

puts addition

#4613732